// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/log/annotation

package main

import (
	"github.com/expgo/log"
)

var (
	logger = log.NewWithTypePathAndConfigPath("github.com/expgo/pipe-mqtt/example", "logging")
)
