// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/factory/annotation

package pipemqtt

import (
	"github.com/expgo/factory"
)

func init() {
	factory.Singleton[MQTT]()
}
